### ISSUE TITLE
点击进入照片裁剪页面崩溃

### ISSUE THREAD

**Issue by zero1222** [wubianxiaoxian/PureCamera-Demo#10]
PureCamerademo[3951:1942245] -[PureCropVC initWithImage:aspectRatioStyle:]: unrecognized selector sent to instance 0x104e01820

**Comment by wubianxiaoxian** [comment]
好的，稍等我看一下

**Comment by zero1222** [comment]
楼主找到问题原因了吗

**Comment by wubianxiaoxian** [comment]
找到了，新的版本 1.6.1 ,修复了这个问题，你可以通过 pod update，或者下载新的 Demo

**Comment by zero1222** [comment]
辛苦了辛苦了，后期可不可以优化成可以纵向拉伸裁剪框^~^

**Comment by zero1222** [comment]
如果照片是从相册中取出来的尺寸比较大的图片裁剪框会有问题

**Comment by wubianxiaoxian** [comment]
具体问题是？读取的图片的分辨率是多大

**Comment by zero1222** [comment]
想适配iphoneX ,然后选一张手机截屏照片，开始裁剪框大小正常，但是收缩一点，裁剪框大小变大了
