### ISSUE TITLE
能不能改成微信的那种的

### ISSUE THREAD

**Issue by lanmeiceo** [wubianxiaoxian/PureCamera-Demo#13]
就是裁剪框是正方形的效果

**Comment by wubianxiaoxian** [comment]
现在的版本，添加了一个
- (instancetype)initWithImage:(UIImage *)image aspectRatioStle:(TOCropViewControllerAspectRatio)style;
现在设置的裁剪比例如下
typedef enum : NSInteger {
    TOCropViewControllerAspectRatioOriginal = 0,
    TOCropViewControllerAspectRatioSquare,
    TOCropViewControllerAspectRatio1x2,
    TOCropViewControllerAspectRatio3x2,
    TOCropViewControllerAspectRatio5x3,
    TOCropViewControllerAspectRatio4x3,
    TOCropViewControllerAspectRatio5x4,
    TOCropViewControllerAspectRatio7x5,
    TOCropViewControllerAspectRatio16x9,
} TOCropViewControllerAspectRatio;
第一次进入 CropView 的时候，可以传入一个指定的裁剪比例

**Comment by lanmeiceo** [comment]
wubianxiaoxian <notifications@github.com>于2018年5月26日 周六14:21写道：

**Comment by lanmeiceo** [comment]
done
