### ISSUE TITLE
swift 下运行, 进入相机页面, 切图资源没有加载

### ISSUE THREAD

**Issue by MQL9011** [wubianxiaoxian/PureCamera-Demo#17]
XCode 10+
swift 4.2 +
pod 引入后 进入相机页面,切图资源没加载出来

**Comment by wubianxiaoxian** [comment]
和 swift 混编？ pod引入后，切图资源没有加载到？

**Comment by MQL9011** [comment]
@wubianxiaoxian 
我用了你PureCamera这个库
其中 在swift 项目中使用PureCamera 会导致切图资源无法找到
我改了源码, 希望作者能更新一版

![image](https://user-images.githubusercontent.com/11871158/56013012-7fbe6980-5d21-11e9-9b74-538b91e02c1b.png)

**Comment by wubianxiaoxian** [comment]
可以，稍后更新

**Comment by wubianxiaoxian** [comment]
pod 'PureCamera', '~> 1.6.2'
更新了你的代码

**Comment by inascf** [comment]
请查看一下我的修改，pod 引入后图片可以正常加载了

**Comment by wubianxiaoxian** [comment]
已 merge
